services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 4455:5432
    env_file:
      - ./back-end/.env.test

  node_app:
    container_name: node_students_app
    build: ./back-end/.env.test
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - ./back-end/.env.test